variables:
  GIT_SSL_NO_VERIFY: "true"

.get-deps: &get-deps |
  # GO DEPS
  for dep in $(cat go_deps);
    do sudo go get -u $dep;
  done


deploy to stage:
  environment: stage
  script:
    - export GO111MODULE=auto;
    - *get-deps
    - sudo go build main.go
    - sudo rm -Rf /var/www/sweethome/backend/*
    - sudo rsync -a main static /var/www/sweethome/backend
    - sudo rsync -a static/env_config_template.json /var/www/sweethome/backend/static/env_config.json
    - sudo systemctl restart sweethome-backend
  only:
    - master
