name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Install Golang
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Golang Ext
          run: |
            go version;
            export GO111MODULE=auto;
            $GOPATH;
            env | grep -E "GO|PATH";
        - name: Checkout code
          uses: actions/checkout@v2
