name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x' ]
    name: Go ${{ matrix.go }} sample
    steps:
        - name: Install Golang
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Golang Ext
          run: |
            go version;
            export GO111MODULE=auto;
            $GOPATH;
            env | grep -E "GO|PATH";
        - name: Checkout code
          uses: actions/checkout@v2
