name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x' ]
    name: Go ${{ matrix.go }}
    steps:
        - name: Install Golang
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Golang Ext
          run: |
            go version;
            export GO111MODULE=off;
            $GOPATH;
            env | grep -E "GO|PATH";
            ls;
        - name: Ls
          run: ls

      #        - name: Go Deps
#          run: |
#            go get github.com/asaskevich/govalidator;
#            go get github.com/jmoiron/sqlx;
#            go get github.com/lib/pq;
#            go get github.com/go-telegram-bot-api/telegram-bot-api;
#            go get github.com/bmizerany/pat;
        - name: Build
          run: go build main.go
        - name: Checkout code
          uses: actions/checkout@v2
